name: 'Graffino Teams Notification'
description: 'Send a custom notification message to a Microsoft Teams channel with GitHub repo details'
author: 'Graffino'
branding:
  icon: message-circle
  color: purple 
inputs:
  github-token:
    description: 'GitHub Token'
    required: true 
  ms-teams-webhook-uri:
    description: 'Microsoft Teams Webhook URI'
    required: true 
  notification-summary:
    description: 'Message to be sent to Microsoft Teams channel'
    required: true 
  timezone:
    description: 'Timezone (ex. Europe/Bucharest)'
    required: false
  timeout:
    description: 'Period after which the action will timeout (in milliseconds) with an error if the notification is not sent'
    required: false 
  job:
    description: 'The stringified job object, used to get the job status and display notification accordingly'
    required: false 
runs:
  using: 'node20'
  main: 'dist/index.js'