name: graffino-teams-notification-test
run-name: ${{ github.actor }} is performing a Graffino Teams Notification test build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "master"
      - "develop"
 
jobs:
  build-test:
    runs-on: [self-hosted, graffino, nodejs]
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]
    steps:
      - name: Checkout
        id: Checkout
        uses: actions/checkout@v4
  
      - uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install NPM Packages
        if: success()
        run: |
          yarn install

      - name: Build Frontend
        if: success()
        run: |
          yarn run build

      - name: Test Deployment
        uses: ./
        with: 
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: "Deployment Started 🚀"
          timezone: Europe/Bucharest
      - name: Test Deployment
        uses: ./
        with: 
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: "Deployment Stopped 🥷🏼"
          timezone: Europe/Bucharest
