name: graffino-teams-notification-test
run-name: ${{ github.actor }} is performing a Graffino Teams Notification test build
on:
  repository_dispatch:
  pull_request:
  push:
    branches:
      - "master"
 
jobs:
  build:
    runs-on: [self-hosted, graffino]
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]
    steps:
      - name: Checkout
        id: Checkout
        uses: actions/checkout@v4
  
      - uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install NPM Packages
        if: success()
        run: |
          yarn install

      - name: Build Frontend
        if: success()
        run: |
          yarn run build
  test:
    runs-on: [self-hosted, graffino]
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      with: 
        github-token: ${{ github.token }}
        ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        notification-summary: Deployment Started 
        notification-color: 17a2b8
        timezone: Bucharest/Romania
    - uses: ./
      with: 
        github-token: ${{ github.token }}
        ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        notification-summary: Warning! Something Not Quite Right 
        notification-color: ffc107
        timezone: Bucharest/Romania
    - uses: ./
      with: 
        github-token: ${{ github.token }}
        ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        notification-summary: OMG!! Something Exploded
        notification-color: dc3545
        timezone: Bucharest/Romania
    - uses: ./
      with: 
        github-token: ${{ github.token }}
        ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        notification-summary: Whew! Everything is right with the world again! 
        notification-color: 28a745 
        timezone: Bucharest/Romania
    - uses: ./
      with: 
        github-token: ${{ github.token }}
        ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        notification-summary: "Emojify! &#x1F6A2​​ &#x2705;"
        notification-color: 28a745 
        timezone: Bucharest/Romania